### ISSUE TITLE
Response body of create (POST), update (PATCH) and replace (PUT) operations is not acccessible

### ISSUE THREAD

**Issue by andreisilviudragnea** [joan38/kubernetes-client#103]
When creating a resource, for example, the user may want to use the resource returned in the response of the POST HTTP call. For now, it is not accessible. Only by issuing a GET request after creation, the created resource can be retrieved.

The problem also exists for update (PATCH) and replace (PUT) operations.

As a comparison, both Java and Skuber clients support this: https://github.com/doriordan/skuber/blob/master/client/src/main/scala/skuber/api/client/KubernetesClient.scala

**Comment by joan38** [comment]
Can you try `0.8.0-7-7d77805-SNAPSHOT` and let us know if that's good?

**Comment by andreisilviudragnea** [comment]
Yes, I will. Thanks for the quick merge ❤️

**Comment by andreisilviudragnea** [comment]
@joan38 I cannot find the release `0.8.0-7-7d77805-SNAPSHOT` in Maven central: https://repo1.maven.org/maven2/ Should I look for it in another Maven repo?

**Comment by joan38** [comment]
https://oss.sonatype.org/content/repositories/snapshots/com/goyeau/kubernetes-client_2.13/0.8.0-7-7d77805-SNAPSHOT/
You need to add the snapshot repo https://oss.sonatype.org/content/repositories/snapshots/

**Comment by andreisilviudragnea** [comment]
I have tested `0.8.0-7-7d77805-SNAPSHOT` and it looks good to me.

**Comment by andreisilviudragnea** [comment]
@joan38 When will a new version with the latest changes be released?

**Comment by joan38** [comment]
`0.8.1` heading to Maven Central.
Thanks!
