### ISSUE TITLE
Publish new version

### ISSUE THREAD

**Issue by petern-sc** [joan38/kubernetes-client#158]
There's been some dependency updates and minor changes that have been merged in the last 12 months but there hasn't been a new version published since October last year. 

Could we get one published? 🙏  @joan38

**Comment by wemrysi** [comment]
I'll second this request, a new release would be most welcome when you have time.

**Comment by joan38** [comment]
Hi guys,

Agree, I was able to fix CI with #165 but I was also trying to make the project work with newer versions of Kubernetes which did not go well and then I was off on vacation.

I'm going to continue trying this upgrade and if it does not work I'll just fix CI which will unblock us to release a new version.

**Comment by joan38** [comment]
[v0.9.0](https://github.com/joan38/kubernetes-client/releases/tag/v0.9.0) baking right now. Let me know if anything is wrong.
