### ISSUE TITLE
How do I  Scale a Statefulset?

### ISSUE THREAD

**Issue by charlesa101** [joan38/kubernetes-client#2]
@joan38 @tomaszym I am trying to scale a stateful set of pods using this API any idea?

**Comment by joan38** [comment]
Hi @charlesa101,

You can do:
```
client.statefulSets.namespace("my-namespace").createOrUpdate(myStatefulSet)
```

If you don't have the stateful set but you just want to set the `replicas` the library doesn't currently support it.
But you can do a `get("name of the stateful set")`, modify the case class and `createOrUpdate(myStatefulSet)`. Note it won't be atomic.

If you or someone want to support this feature, it would probably be a matter of implementing a new trait `Scalable` with a function `scale(replicas: Int)` and implement it in `NamespacedStatefulSetsOperations` and probably `NamespacedDeploymentsOperations` and `NamespacedReplicaSetsOperations`.

Hope it helps.

**Comment by charlesa101** [comment]
cool @joan38 thanks that explains it! but what will the stucture of `myStatefulSet` look like ?

**Comment by joan38** [comment]
It's going to be a `io.k8s.api.apps.v1beta2.StatefulSet` you should be able to see this in your IDE.
This is a generated case class from the [swagger file](https://github.com/joan38/kubernetes-client/blob/master/src/main/swagger/swagger.json) that we copy from the official [Kubernetes swagger](https://github.com/kubernetes/kubernetes/blob/master/api/openapi-spec/swagger.json).
This is one of the reasons why this client is easily upgradable to newer versions of Kubernetes.

Let mw know if you have more questions, happy to answer!

**Comment by charlesa101** [comment]
Thanks @joan38  do you have any sample structure for statefulset?

**Comment by joan38** [comment]
The structure should be exactly the same as the YAML version but with the Scala syntax:
```
StatefulSet(
  metadata = Option(ObjectMeta(name = "elasticsearch")),
  spec = Option(
    StatefulSetSpec(
      selector = Option(LabelSelector(matchLabels = appElasticsearchLabel)),
      serviceName = internalService.metadata.get.name.get,
      replicas = Option(3),
      updateStrategy = Option(StatefulSetUpdateStrategy(`type` = Option("RollingUpdate"))),
      podManagementPolicy = Option("Parallel"),
      template = PodTemplateSpec(
        metadata = Option(ObjectMeta(labels = appElasticsearchLabel)),
        spec = Option(
          PodSpec(
            affinity = Option(
              Affinity(
                podAntiAffinity = Option(
                  PodAntiAffinity(
                    requiredDuringSchedulingIgnoredDuringExecution = Option(
                      Seq(
                        PodAffinityTerm(
                          labelSelector = Option(
                            LabelSelector(
                              matchExpressions = Option(
                                Seq(
                                  LabelSelectorRequirement(
                                    key = "app",
                                    operator = "In",
                                    values = Option(Seq("elasticsearch"))
                                  )
                                )
                              )
                            )
                          ),
                          topologyKey = Option("failure-domain.beta.kubernetes.io/zone")
                        )
                      )
                    )
                  )
                )
              )
            ),
            containers = Seq(
              Container(
                name = "elasticsearch",
                image = Option(image),
                env = Option(
                  Seq(
                    EnvVar(name = "cluster.name", value = Option("elasticsearch")),
                    EnvVar(
                      name = "node.name",
                      valueFrom =
                        Option(EnvVarSource(fieldRef = Option(ObjectFieldSelector(fieldPath = "metadata.name"))))
                    ),
                    EnvVar(name = "discovery.zen.ping.unicast.hosts", value = internalService.metadata.get.name),
                    EnvVar(name = "xpack.security.enabled", value = Option(false.toString)),
                    // Index settings
                    EnvVar(name = "indices.query.bool.max_clause_count", value = Option(6144.toString)),
                    // Lock page swapping
                    // EnvVar(name = "bootstrap.memory_lock", value = Option(true.toString))
                  )
                ),
                volumeMounts = Option(Seq(VolumeMount(name = "data", mountPath = "/usr/share/elasticsearch/data")))
              )
            ),
            securityContext = Option(PodSecurityContext(runAsUser = Option(1000), fsGroup = Option(1000)))
          )
        )
      ),
      volumeClaimTemplates = Option(
        Seq(
          PersistentVolumeClaim(
            metadata = Option(ObjectMeta(name = Option("data"))),
            spec = Option(
              PersistentVolumeClaimSpec(
                accessModes = Option(Seq("ReadWriteOnce")),
                resources = Option(ResourceRequirements(requests = Option(Map("storage" -> Quantity("100Gi")))))
              )
            )
          )
        )
      )
    )
  )
)
```

I'm not particularly proud of these case classes but this reflects the mess of the Kubernetes model.

**Comment by charlesa101** [comment]
Cool thank you!

Yeah no easy way around it because of the Kubernetes YAML i agree!

**Comment by charlesa101** [comment]
Also do i have to do all this even if i am scaling an existing pod already in my NS ?

**Comment by joan38** [comment]
Actually you can omit all optional fields if this is for an update.
It will do a `PATCH` request with a `merge-patch+json` according to:
https://github.com/joan38/kubernetes-client/blob/master/src/main/scala/com/goyeau/kubernetes/client/CommonOperations.scala#L26-L29

So it should just add or override the defined fields 😄.

**Comment by charlesa101** [comment]
Yeah I finally got it working with a new POD but it won't scale on existing pod already implemented and deployed on our cluster with helm charts! 

Thanks a lot!
