### ISSUE TITLE
diverging implicit expansion for type cats.effect.Sync[F], catsReaderWriteStateTSync

### ISSUE THREAD

**Issue by anandsahil** [joan38/kubernetes-client#21]
When I am initializing the client I get this error, here is a scastie for this "**diverging implicit expansion for type cats.effect.Sync[F] starting with method catsReaderWriteStateTSync in object Sync**"

https://scastie.scala-lang.org/v3mfwfZaTNqwmpQvUCIZQw

```scala  import cats.effect.Sync._
  import com.goyeau.kubernetes.client._
  import io.chrisdavenport.log4cats.Logger
  import io.chrisdavenport.log4cats.slf4j.Slf4jLogger
  import io.k8s.api.apps.v1._
  import io.k8s.api.core.v1._
  import io.k8s.apimachinery.pkg.api.resource.Quantity
  import io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
  import java.io.File
  import scala.concurrent.ExecutionContext
  import cats.effect.{ContextShift, IO, Timer}

  implicit val timer: Timer[IO] = IO.timer(ExecutionContext.global)
  implicit val contextShift: ContextShift[IO] = IO.contextShift(ExecutionContext.global)
  implicit val logger: Logger[IO] = Slf4jLogger.getLogger[IO]
  val config = KubeConfig(new File(s"${System.getProperty("user.home")}/.kube/config"))


  val kubernetesClient = KubernetesClient[IO](config)`

**Comment by joan38** [comment]
Thanks for reporting this and the effort of making a Scastie.

It seems Scala is not able to resolve the the `[IO]` on `KubeConfig`.
So if you replace:
```scala
val config = KubeConfig(new File(s"${System.getProperty("user.home")}/.kube/config"))
```
by:
```scala
val config = KubeConfig[IO](new File(s"${System.getProperty("user.home")}/.kube/config"))
```
It works, otherwisze it's trying to resolve `F` as `Nothing` is guess.

The documentation is off and I will fix it now.

**Comment by anandsahil** [comment]
> Thanks for reporting this and the effort of making a Scastie.
> 
> It seems Scala is not able to resolve the the `[IO]` on `KubeConfig`.
> So if you replace:
> 
> ```scala
> val config = KubeConfig(new File(s"${System.getProperty("user.home")}/.kube/config"))
> ```
> 
> by:
> 
> ```scala
> val config = KubeConfig[IO](new File(s"${System.getProperty("user.home")}/.kube/config"))
> ```
> 
> It works, otherwisze it's trying to resolve `F` as `Nothing` is guess.
> 
> The documentation is off and I will fix it now.

Yes, I tried it after it and I also came to the same conclusion, it worked after adding explicit type. Helping compiler do its task. :-) @joan38 thank you for the quick reply.
