### ISSUE TITLE
Transitive Dependencies (v 0.4.0)

### ISSUE THREAD

**Issue by odenzo** [joan38/kubernetes-client#24]
I am getting slf4j conflicts, apparently because you are exporting logbook-classic as a dependency instead of just slf4j-api.

ps. Looking at that I also notice that the transitive dependency include both http4s AND Akka-http and Akka-stream.
Not sure this is transition phase, as I see the notes that you were converting to http4s?

Submit this in the spirit of request for feedback, as can fix by excluding the logbook-classic in my sbt.
i..e
```
val lib_k8s = Seq("com.goyeau" %% "kubernetes-client" % kubernetesClientV).map(_.exclude("ch.qos.logback", "*"))
```

**Comment by joan38** [comment]
Thanks for reporting this!
I removed `logback-classic` from our deps #26
For Akka, we have no mention of the word "akka" in our entire codebase so that must be coming from somewhere else.
