### ISSUE TITLE
Incorrect `AuthInfoExec` model

### ISSUE THREAD

**Issue by jchapuis** [joan38/kubernetes-client#242]
I believe that the `env` field in  

```scala
case class AuthInfoExec(
    ...,
    env: Option[Map[String, String]],
    ...
)
```

should rather by typed with smth like

`List[Map[String, String]]`

as this is a list in the config API. 

At the moment, parsing a valid config with 

```yaml
 env:
      - name: AWS_PROFILE
        value: Dev
```

leads to the following decoding error:

`DecodingFailure at .users[0].user.exec.env: Got value '[{"name":"AWS_PROFILE","value":"Dev"}]' with wrong type, expecting object`

**Comment by yurique** [comment]
Interesting. I must have misread the spec when implementing this initially. 

For reference, here's the spec: https://kubernetes.io/docs/reference/config-api/kubeconfig.v1/#ExecConfig

It does say that `env` is an array of `ExecEnvVar`, with `ExecEnvVar` being an object with two fields: `name` and `value`.

I'll prepare a PR with a fix later today.

**Comment by yurique** [comment]
@jchapuis: I just opened a PR addressing this (https://github.com/joan38/kubernetes-client/pull/243).

I don't have a kubeconfig that has env vars specified, so not sure how to test this.

Would you be willing to publish-local and test it out? :) 

```
./mill kubernetes-client[2.13.10].publishLocal
```

**Comment by jchapuis** [comment]
@yurique great thanks for the quick answer and fix! will try it now

**Comment by jchapuis** [comment]
perfect it's working, i've tested it with my config which has the pattern I mentioned here. Thanks for the super quick fix!

**Comment by yurique** [comment]
Awesome! I can't release it, so we'll have to wait for @joan38 to get some time to spare :) 


There's also a couple of other PRs that would be nice to have released as well:

* https://github.com/joan38/kubernetes-client/pull/238
* https://github.com/joan38/kubernetes-client/pull/223

**Comment by joan38** [comment]
Hi guys, Sorry for the late answer here, I've been busy upgrading projects at work to Scala 3 😃 
Thanks @jchapuis for reporting the bug and thanks @yurique for the fix and all other PRs too.

**Comment by jchapuis** [comment]
@joan38 any chance for a release including this fix? 🙏

**Comment by joan38** [comment]
Looking at the 2 PRs from @yurique and will make a release
