### ISSUE TITLE
Can you give me an example of how to simply output a list of pods?

### ISSUE THREAD

**Issue by bench87** [joan38/kubernetes-client#248]
You're a developer who wrote scalar code a long time ago. Can you give me a simple example so I can get a feel for writing scalar code?
The code below is what I wrote, but it doesn't work.
```
import cats.effect.{IO, IOApp}
import com.goyeau.kubernetes.client.*
import io.k8s.api.apps.v1.*
import io.k8s.api.core.v1.*
import io.k8s.apimachinery.pkg.api.resource.Quantity
import io.k8s.apimachinery.pkg.apis.meta.v1.ObjectMeta
import org.typelevel.log4cats.Logger
import org.typelevel.log4cats.slf4j.Slf4jLogger

import java.io.File
import scala.concurrent.ExecutionContext
import scala.concurrent.duration.*
implicit val logger: Logger[IO] = Slf4jLogger.getLogger[IO]

object HelloWorld extends IOApp.Simple {


  val run = {
    val kubernetesClient = KubernetesClient[IO](KubeConfig.standard[IO])
    val podListIO = kubernetesClient.use(_.pods.namespace("infra").listDecoder)
  }
}
```

**Comment by joan38** [comment]
```
kubernetesClient.use(_.pods.namespace("infra").list())
```
?

**Comment by bench87** [comment]
> ```
> kubernetesClient.use(_.pods.namespace("infra").list())
> ```
> 
> ?

sorry I'm a very novice scalar developer, so the code I wrote above is probably completely wrong. If you can give me a simple pod list example, I'll start with that code snippet and try to build what I want.

**Comment by bench87** [comment]
Sorry about that. It seems that my IDE settings were incorrect and the autocomplete was not working and I was having trouble writing code because of it. I'm closing this issue.

**Comment by joan38** [comment]
Glad it helps!
