### ISSUE TITLE
[Beginner Question]. Results Types Lost / More Examples

### ISSUE THREAD

**Issue by odenzo** [joan38/kubernetes-client#25]
Just testing this library out for usage with AWS.
I construct the configuration and client ok, and can run, e.g.

```
    val config: IO[KubeConfig]                     = KubeConfiguration.clientFromConfigWithAwsToken(context)
    val client: Resource[IO, KubernetesClient[IO]] = Kube.createLiftedClient(config)
    val result = client.use { client =>
     
     val res: IO[_] = client.namespaces.list() 

     res 
    }
 result.attempt.unsafeRunSync()
```

I am actually getting the correct answer if I log it,  but loosing the type information, which is `F[Resource]` and `Resource[F,A]`.
Think something basic about the Tagless Final stuff I am misunderstanding. 
This is the correct way to invoke stuff?  Of course I want to get the namespaces and do some stuff etc etc within the resource usage bracket. 

Any pointers or perhaps a slightly evolved example for the docs. Looked at the test cases to no avail.

**Comment by joan38** [comment]
I might have misunderstood the question but the following compiles fine for me:
```
  val config: IO[KubeConfig]                     = ???
  val client: Resource[IO, KubernetesClient[IO]] = ???
  val result = client.use { client =>

    val res: IO[NamespaceList] = client.namespaces.list()

    res
  }
  result.attempt.unsafeRunSync()
```

**Comment by odenzo** [comment]
> I might have misunderstood the question but the following compiles fine for me:
> 
> ```
>   val config: IO[KubeConfig]                     = ???
>   val client: Resource[IO, KubernetesClient[IO]] = ???
>   val result = client.use { client =>
> 
>     val res: IO[NamespaceList] = client.namespaces.list()
> 
>     res
>   }
>   result.attempt.unsafeRunSync()
> ```

My apologies, and you understood correctly.  It was IntelliJ not inferring, and giving me an highlighting error when labelling val res:IO[Namespace].   (IJ 2020.1.2 for posterity). 

Thanks for building this tool

**Comment by joan38** [comment]
Idea is strange sometimes, I never believe it.
Glad you like it :)
