### ISSUE TITLE
migrate to sbt?

### ISSUE THREAD

**Issue by yurique** [joan38/kubernetes-client#261]
@joan38 what do you think about migrating the build (back) to `sbt`?

Less people know how to work with `mill` (including me :) ).
On the other hand, there's a ton of knowledge/experience in the community (especially in the typelevel community) with maintaining `sbt` projects, including cross-platform builds. 

For `sbt` we also have quite a few plugins that make maintaining easier (github actions automation, bin-compat validation, etc).

Happy to jump on it.

**Comment by armanbilge** [comment]
> For `sbt` we also have quite a few plugins that make maintaining easier (github actions automation, bin-compat validation, etc).

I highly-recommend sbt-typelevel which completely automates that.

https://typelevel.org/sbt-typelevel/

**Comment by joan38** [comment]
To be fair, I was thinking more to go on scala-cli rather than any build tool.

About SBT, for me it's very hard to understand the magic going on and really liked Mill as it's not rocket science but just Scala (to me).

**Comment by yurique** [comment]
Fair enough :)

While I'd prefer sbt, I don't feel strongly about switching to it here - the build is rather simple, so it should be fine.
