### ISSUE TITLE
Instantiate PODs/SERVICES/STATEFULSETS from Yaml 

### ISSUE THREAD

**Issue by charlesa101** [joan38/kubernetes-client#3]
[Feature]
It will be nice to have the API be able to deploy from a defined YAML or JSON definitions of the Pods, Services or ingress

**Comment by novakov-alexey-zz** [comment]
I guess, you mean loading yaml template from file in runtime and applying it from Scala? Otherwise, why not use kubectl for that then :-) ?

**Comment by joan38** [comment]
Indeed you can easily do:
```scala
import sys._
"kubectl ...".!
```
But kubectl has to be installed on the machine.

**Comment by joan38** [comment]
I'm closing this as it's unlikely we'll implement a yaml parser in this repo. The min case would be executing a `kubectl` command but that wouldn't add much value over a `"kubectl ...".!` call.

Thanks for the suggestion tho!
