### ISSUE TITLE
List Resources based on Label Selector

### ISSUE THREAD

**Issue by mohnishkodnani** [joan38/kubernetes-client#5]
Hi, 
Is there a way to say list statefulset or any other resource within a namespae but also based on labels. 
I see we can do the following 
```kubeContext.statefulSets.namespace(namespace).list```
However, I might have to then apply a filter on top of these, I rather k8s just return based on label selector. 
I couldnt find an example of that.

**Comment by joan38** [comment]
Super late answer but the library doesn't support filtering/querying capability.
But I can see that the API does: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#api
We could add this capability on this lib.

**Comment by joan38** [comment]
Thanks to @novakov-alexey we now support filtering based on Label Selector
