### ISSUE TITLE
New Kubernetes version support

### ISSUE THREAD

**Issue by novakov-alexey-zz** [joan38/kubernetes-client#7]
Latest stable Kubernetes release is 1.18: https://kubernetes.io/docs/setup/release/notes/

I can propose a PR with 1.18 swagger.json and few fixes: https://github.com/novakov-alexey/kubernetes-client/tree/upgrade-to-k8s-v1.18

What is overall strategy to for kubernetes-client to support newer version of Kubernetes API? Should it just replacement and fixed (if needed) of current code?

**Comment by joan38** [comment]
Thanks will have a look at the PR now.

> What is overall strategy to for kubernetes-client to support newer version of Kubernetes API? Should it just replacement and fixed (if needed) of current code?

The Kubernetes API is never breaking as far as I know. So if we just upgrade to the latest we should benefit from their deprecations cycles and be safe.

But it's worth noting that we don't maintain any map table of which kubernetes-client version to supported Kubernetes API in the readme.

**Comment by novakov-alexey-zz** [comment]
Right, that is my understanding too, that breaking changes are quite rare. Ok, then my second PR is doing exactly this - upgrade to latest stable version.

**Comment by joan38** [comment]
Fixed by #11  thanks @novakov-alexey
