### ISSUE TITLE
Handle potential exception in KubeConfig

### ISSUE THREAD

**Issue by PawelJ-PL** [joan38/kubernetes-client#78]
Hi,

There are potential exception in KubeConfig case class constructor (https://github.com/joan38/kubernetes-client/blob/master/kubernetes-client/src/com/goyeau/kubernetes/client/KubeConfig.scala#L22).

I've prepared two MRs with two different solutions:

* https://github.com/joan38/kubernetes-client/pull/76 - constructor can be private and instance can be created in effect by companion object
* https://github.com/joan38/kubernetes-client/pull/77 - exception can be avoided when certificate will be instance of sealed trait

**Comment by yurique** [comment]
Since the PR was merged, I'm assuming this is fixed :)
