### ISSUE TITLE
Need a build for scala version 2.11

### ISSUE THREAD

**Issue by anirudh-simha** [joan38/kubernetes-client#89]

**Comment by novakov-alexey-zz** [comment]
@anirudh-simha do you really need 2.11 support? If - yes, can you clarify why?
I would even drop support for 2.12 and focused on 2.13 and 3 support only.

**Comment by joan38** [comment]
Sorry Scala 2.11 is very much EOL at this point and supporting it would be too much hassle nowadays.
We aim at supporting 2 or 3 version at a time and as @novakov-alexey mentioned even 2.12 is arguable.
